### ISSUE TITLE
Can you upload  file of discretize.m?

### ISSUE THREAD

**Issue by Jiang1206** [candicei/MATLAB-ElT#1]
project_eit.m can not run without discretize.m. And  I don't known how to achieve it.

**Comment by candicei** [comment]
Hi Jiang1206, 

The function "discretize.m" is a part of MATLAB. It was introduced in 2015a. You may have to update your MATLAB if it's an earlier version, or find the actual .m file from MATLAB. Here's the page for the function: [https://www.mathworks.com/help/matlab/ref/discretize.html](https://www.mathworks.com/help/matlab/ref/discretize.html)
